### ISSUE TITLE
HOW DO I CLOSE THIS PROGRAM TO ACCESS WINDWOS AGAIN

### ISSUE THREAD

**Issue by GXNEVER** [PAXANDDOS/ForzaHorizon4Fix#3]
HOW DO I CLOSE THIS PROGRAM TO ACCESS WINDWOS AGAIN

**Comment by PAXANDDOS** [comment]
I'm not sure what do you mean... Please explain more in more detail.
Usually, the program closes as soon as you close your Forza Horizon game. Some bugs may happen if you started this program, closed the Forza Horizon game, and was pressing Ctrl+C on the terminal window. Anyways if you were left on black/gray screen without the explorer, then press Ctrl+Shift+Esc, select File -> Start the new task, and type `explorer.exe`.

**Comment by PAXANDDOS** [comment]
Closed due to inactivity and lack of information, please open again if the issue is still relevant.
