### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by EgyptWaffleS** [PAXANDDOS/ForzaHorizon4Fix#4]
This for forza horizon 4 and windows 10, I've tried both versions but the game doesn't even last for a minute.

**Comment by PAXANDDOS** [comment]
Is the issue still relevant? If so, can you explain in more detail? You're the first one reporting that, so the problem may be on your side. After the start of the script, the game should launch first before killing the explorer.exe, maybe your game takes more time to launch? If not, can you check the task manager (Ctrl+Shift+Esc) if there are any explorer.exe processes?

**Comment by PAXANDDOS** [comment]
Closed due to inactivity. Please reopen if the issue is still relevant.
