### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by M0nthe** [PAXANDDOS/ForzaHorizon4Fix#7]
As the title says, it's just not working for me, I need some help

**Comment by PAXANDDOS** [comment]
Hi! Can you describe it in more detail? 
- What OS do you have?
- Do you run FH4 or FH5?
- Where did you get that Forza Horizon game? Steam or Microsoft Store? Have to note that this script is only for Microsoft Store versions
- What is the flow? You run the script which runs the game, does the explorer process get killed? Does the script run in the background? Or what exactly happens?

**Comment by M0nthe** [comment]
Yes, of course...

- Windows 11 Pro N
- FH5
- Microsoft Store
- Scripts runs perfectly, explorer process gets killed, but after about 30 minutes game just crashes

I have been trying to solve this problem for three days now, I have tried reinstalling xbox programs (e.g. gaming services, xbox game bar). Somehow I managed to play once without crashes, and hoped that the game will continue to work properly, but from the next launch I was disappointed. I've been playing forza for a few years now, and usually all problems were solved by a fix that turns off explorer, but now it doesn't help. I'm looking for some help

Update:
I was looking for some fix and I found, that I can see the error in Event Viewer, but I'm still can't get game work properly.

Event Viewer error:

Faulting application name: ForzaHorizon5.exe, version: 0.0.0.0, time stamp: 0x646573ca
Faulting module name: ForzaHorizon5.exe, version: 0.0.0.0, time stamp: 0x646573ca
Exception code: 0xc0000005
Fault offset: 0x0000000000922fac
Faulting process id: 0x0x7568
Faulting application start time: 0x0x1D9A2E7ECA2EC1C
Faulting application path: C:\Program Files\WindowsApps\Microsoft.624F8B84B80_3.588.95.0_x64__8wekyb3d8bbwe\ForzaHorizon5.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.624F8B84B80_3.588.95.0_x64__8wekyb3d8bbwe\ForzaHorizon5.exe
Report Id: 1b479238-bf97-4b7f-a6b3-932bac639af7
Faulting package full name: Microsoft.624F8B84B80_3.588.95.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: Forzahorizon5

**Comment by M0nthe** [comment]
I solved a problem. Thanks for trying to help me

**Comment by PAXANDDOS** [comment]
> I solved a problem. Thanks for trying to help me

Hi again!

Can I ask you how did you fix the issue?
I know it's been some time but at the time you reported that I didn't know anything about your issue or how to reproduce it. And recently me and several other people started facing the same issue, the same exception code, and nothing helps. Could use your assistance

**Comment by M0nthe** [comment]
I'm not sure what exactly caused the fix, I tried a lot of things I don't remember all of them (I'll check what I did later when I'm home). But I think the fix was disabling the Nvidia Instant Replay feature.

**Comment by M0nthe** [comment]
Sorry it's too late, I forgot. I was hoping to look in the browser history to see what I did, but there's so many different forza related actions that it's impossible to understand anything. I think disabling Nvidia Instant Replay was the fix for me, maybe I'll find something more

**Comment by PAXANDDOS** [comment]
Hmm, interesting, but I don't even use GeForce Experience... Thanks anyways!

**Comment by M0nthe** [comment]
I remembered, my friend fixed that by using windows secure boot
